import Head from "next/head";
import { Hero } from "@/components/pages/home/hero/Hero";
import { HomeMenu } from "@/components/pages/home/homeMenu/HomeMenu";
import { About } from "@/components/pages/home/about/About";
import { Testimonials } from "@/components/pages/home/testimonials/Testimonials";

export default function Home() {
	return (
		<>
			<Head>
				<title>Luck Tory</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<HomeMenu />
			<About />
			<Testimonials />
		</>
	);
}
